### ISSUE TITLE
Game log spammed with NRE

### ISSUE THREAD

**Issue by Aivech** [linuxgurugamer/ksp-precisenode#10]
Game version 1.7.1.2539
No DLC
```
[EXC 21:15:54.085] NullReferenceException: Object reference not set to an instance of an object
	RegexKSP.IntuitiveNodeGizmoHandler.AttachHandleHandlers ()
	RegexKSP.IntuitiveNodeGizmoHandler.OnUpdate ()
	RegexKSP.IntuitiveNodeGizmosManager.OnUpdate ()
	RegexKSP.PreciseNode.Update ()
```

**Comment by linuxgurugamer** [comment]
A bit more context, please.  What scene were you in?  What were you doing, etc.

**Comment by linuxgurugamer** [comment]
As reported to me by someone else:

1.  In mapview, make a node
2. Switch to flight scene

then nullrefs

**Comment by Aivech** [comment]
I'm not sure. I noticed it trying to diagnose unusually bad framerate, opened up the game log, and saw a few hundred thousand lines of nullrefs.

**Comment by linuxgurugamer** [comment]
Fixed
