### ISSUE TITLE
Does not Work with KSP 1.8

### ISSUE THREAD

**Issue by dodson618** [linuxgurugamer/ksp-precisenode#12]
I've tried every combination I can think of copying GameData/Precise Node and Precise Node (top level directory) to GameData in my KSP install folder on both 1.8.0 and 1.8.1.  On 1.8.0, I do get a notice when launching KSP asking if Precise Node can check for updates, but none of the precise node features work in-game.

**Comment by linuxgurugamer** [comment]
It would be better to post in the forum, that way other people can help as well.
It would also help if you provided a log file.

**Comment by dodson618** [comment]
Apologies. Checked the forum--had an issue with dependencies.  Works now in 1.8.1

**Comment by linuxgurugamer** [comment]
Glad to hear it was simple to fix
