### ISSUE TITLE
Enabling "Intuitive Maneuvers" results in NRE spam

### ISSUE THREAD

**Issue by AkiraR** [linuxgurugamer/ksp-precisenode#14]
What is says on the tin.

repro:
-open precise node window
-open options
-check the Intuitive Maneuvers box
-check log and see NRE spam

This is the NRE, git and gist are complaining about the logs file size so I will update this when I make a new one that isn't after about 2 hours of play and has a little over 500,000 lines.

[EXC 00:25:55.711] NullReferenceException: Object reference not set to an instance of an object
	RegexKSP.IntuitiveNodeGizmoHandler.OnUpdate () (at <02a072ff6cd84a48b6a46074446e9a4b>:0)
	RegexKSP.IntuitiveNodeGizmosManager.OnUpdate () (at <02a072ff6cd84a48b6a46074446e9a4b>:0)
	RegexKSP.PreciseNode.Update () (at <02a072ff6cd84a48b6a46074446e9a4b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by linuxgurugamer** [comment]
Thank you, this is an excellent report.  I'll look at it asap

**Comment by linuxgurugamer** [comment]
Please see the thread, I can't reproduce this, need more info, and since there are others experiencing this, I think the thread is a better place to discuss for now.  But thank you for getting me the initial data

**Comment by linuxgurugamer** [comment]
I'll leave this open until it's fixed.
