### ISSUE TITLE
Installation Checker is (Too?) Strict on Path

### ISSUE THREAD

**Issue by CMDRLucienn** [linuxgurugamer/ksp-precisenode#15]
Small, silly issue that is probably very low priority, but reporting it for completeness sake.

Came back to KSP after a number of years, and updated Precise Node through CKAN - which, as far as I can tell, overwrites the installation directory for the mod with the new files. I manually made sure there was no leftover old files too, to be sure.

After this, I received this error message on launch:

![2020-10-13_03-06-53](https://user-images.githubusercontent.com/7802122/95851808-05084d00-0d10-11eb-9ec9-359a4ae5c92a.png)

A quick investigation later; some older versions of Precise Node used **plugins** as the path instead of **Plugins**, and windows doesn't seem to care about the case in the path when overwriting. 

Simply renaming folder plugins to Plugins fixes the issue.

**Comment by linuxgurugamer** [comment]
Your problem arose because you didn't remove the old one entirely.  The current release has Plugins in the file, and that's needed because some Macs and all Linux both are case sensitive.   Windows doesn't care about the case, so it updated properly, but the directory name didn't get updated

This isn't a problem, it's by design.

Just tested it on a new install, works fine

also, when you are asking for help, please post in the forum, not here.  This is meant for real issues which have been proven to be bugs, or feature request.  Just saying something isn't working without any indication that it's a bug is a waste of both of our times.  If you had posted on the forum, you have the possibility of having someone else give you an answer before I can

**Comment by dented42** [comment]
I'm not convinced this should be closed... I just installed this on a fresh KSP with no previous version of PreciseNode and am getting almost exactly the same error on my MacBook Air.

<img width="331" alt="image" src="https://user-images.githubusercontent.com/497149/125386345-586c0200-e359-11eb-8c79-bd58b8f2019f.png">

It seems like it's not liking being located in the Plugins folder? But if it's able to load the plugin enough to know that it doesn't want to be there then surely it should be happy enough being in the plugins folder?

**Comment by dented42** [comment]
Moving the plugin to `KSP_osx/GameData/PreciseNode` does make the error go away (though opening a new node doesn't seem to make the expected UI popup but It's possible I'm not understanding what little documentation exists), but regardless even if that fixes it having a plugin not want to be in the plugins directory seems like incorrect behaviour and should be corrected.

**Comment by linuxgurugamer** [comment]
Log file, please.  I still think you have an old version from somewhere, how did you create the "fresh" version of KSP?
I just installed it using CKAN into a totally clean install, and it's fine.  If you are using a Steam install, you most likely have old DLLs left over
And again, I'll repeat, would be better to post these things in the forum, where you can get more help from other people besides myself

**Comment by dented42** [comment]
I downloaded the game from the website and unzipped it. I then unzipped what I'm fairly certain is the most recent version  ([`PreciseNode-1.8.0-1.2.11.1.zip`](https://github.com/linuxgurugamer/ksp-precisenode/releases/tag/1.2.11.1)) into the Plugins folder.

I'm in the middle of a flight right now but when I'm finished I'll do some debugging and grab the logs.

**Comment by dented42** [comment]
The following logs were generated with the following steps:

1. Launching the game (from within KSPLauncher which was itself run from a `zsh` shell).
2. Waiting for the main menu to load. 
3. Loading my main career game.
4. Switching to an orbiting vessel from the tracking station.
5. Creating a new maneuver node.
6. Pressing 'o'.
7. Pressing 'p'.
8. Quit to main menu.
9. Exiting the game.

First without PreciseNode (or click through blocker) anywhere:
[KSP-vanilla.log](https://github.com/linuxgurugamer/ksp-precisenode/files/6805921/KSP-vanilla.log)

With PreciseNode (and click through blocker) in the Plugins directory:
[KSP-plugins.log](https://github.com/linuxgurugamer/ksp-precisenode/files/6805943/KSP-plugins.log)

With PreciseNode (and click through blocker) in the GameData directory:
[KSP-gamedata.log](https://github.com/linuxgurugamer/ksp-precisenode/files/6805965/KSP-gamedata.log)

**Comment by CMDRLucienn** [comment]
The correct installation is indeed GameData/PreciseNode/Plugins/PreciseNode.dll, which is the third log you posted, and the one which does not generate the path error that I originally posted. As for why it doesn't work there, that's what requires further investigation.

The reason you aren't receiving any errors by putting other mods (ClickThroughBlocker) in the Plugins folder is because for most mods, KSP is not too strict with paths, and that seems to be the case with ClickThroughBlocker. This is what prompted me to create this issue initially; I thought it was unintended behaviour that PreciseNode was so picky (to the point of being case sensitive). Indeed, when you install it to the GameData/Plugins folder, PreciseNode does identify that it exists just fine, because it is still loaded by the game. However, linuxgurugamer's explanation makes it clear that PreciseNode is one of those exceptions that makes it quite strict over its path.

To reiterate for clarity: GameData/Plugins/PreciseNode is an incorrect install; GameData/PreciseNode is a correct install.

**Comment by linuxgurugamer** [comment]
Ummm, NO MOD SHOULD BE IN       GameData/Plugins 
PERIOD.

That is a leftover from the early days of KSP.
All mods should be installed into the main GameData directory.

Almost all of my mods have the InstallChecker code installed, which checks to see that they are installed into the correct directory.  Looks like I missed adding it to the ClickThroughBlocker, that will be rectified in the next release

Reasons like this are why I strongly recommend installing all of my mods using CKAN, it installs everything into the correct directory

@CMDRLucienn for your response
